var COMMANDS = {
  OPEN_CART: "OPEN_CART",
  CLOSE_CART: "CLOSE_CART",
  CHECK_OUT: "CHECK_OUT",
  ADD_TO_CART: "ADD_TO_CART",
  SEARCH_PRODUCT: "SEARCH_PRODUCT",
  PRODUCT_DETAIL: "PRODUCT_DETAIL",
  REMOVE_PRODUCT : 'REMOVE_PRODUCT',
};
export default COMMANDS;
